import { useLanguage } from "../contexts/LanguageContext";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { ArrowLeft, FileText, AlertTriangle, CreditCard, Scale, Globe } from "lucide-react";

const TermsPage = () => {
  const { language, setLanguage } = useLanguage();
  const lastUpdated = "20 Ocak 2026";

  const content = {
    tr: {
      title: "Kullanim Sartlari",
      subtitle: "Hizmet kosullari ve sorumluluklar",
      lastUpdated: `Son guncelleme: ${lastUpdated}`,
      intro: `Bu kullanim sartlari, CAELINUS AI ("biz") tarafindan sunulan AskSanri uygulamasinin ("uygulama") kullanimini duzenler. Uygulamayi kullanarak bu sartlari kabul etmis olursunuz.`,

      sections: [
        {
          icon: FileText,
          title: "Hizmet Tanimi",
          content: `AskSanri, yapay zeka destekli kisisel gelisim ve oz-yansima aracidir.

\u2022 Uygulama, bilinc analizi, sembol yorumlama, rituel rehberligi ve numeroloji gibi ozellikler sunar.
\u2022 Tum icerikler yapay zeka tarafindan uretilir ve genel bilgilendirme amaclidir.
\u2022 Uygulama, profesyonel psikoloji, tip, hukuk veya finansal danismanlik hizmeti DEGILDIR.
\u2022 Kullanici, uygulama iceriklerini kendi sorumlulugunda degerlendirmelidir.`
        },
        {
          icon: AlertTriangle,
          title: "Kullanici Sorumluluklari",
          content: `\u2022 Uygulamayi yasalara uygun sekilde kullanmayi kabul edersiniz.
\u2022 Hesabinizin guvenliginden siz sorumlusunuz.
\u2022 Kotu amacli, yaniltici veya zarli icerik olusturmak yasaktir.
\u2022 Diger kullanicilarin deneyimini olumsuz etkileyecek davranislardan kacinmalisiniz.
\u2022 13 yasindan kucuk bireyler uygulamayi kullanamazlar.`
        },
        {
          icon: CreditCard,
          title: "Abonelik ve Odemeler",
          content: `\u2022 Uygulama ucretsiz ve premium katmanlar sunar.
\u2022 Premium abonelik Apple App Store veya Google Play Store uzerinden yonetilir.
\u2022 Abonelik aylik olarak otomatik yenilenir.
\u2022 Iptal islemleri cihazinizin hesap ayarlarindan yapilir.
\u2022 Iptal edilen abonelik, mevcut donem sonuna kadar aktif kalir.
\u2022 Iade politikasi Apple ve Google'in standart iade politikalarina tabidir.`
        },
        {
          icon: Scale,
          title: "Fikri Mulkiyet",
          content: `\u2022 Uygulama icerigi, tasarimi ve kodu CAELINUS AI'a aittir.
\u2022 Kullanici, kisisel kullanim disinda icerigi cogaltamaz veya dagitamaz.
\u2022 Yapay zeka tarafindan uretilen icerikler bilgilendirme amaclidir; ticari kullanim icin izin gereklidir.`
        },
        {
          icon: Globe,
          title: "Sorumluluk Sinirlamasi",
          content: `\u2022 Uygulama "oldugu gibi" sunulur, belirli bir sonuc garanti edilmez.
\u2022 Yapay zeka iceriklerinin dogrulugu garanti edilmez.
\u2022 Uygulama kullanimi sonucu olusabilecek dogrudan veya dolayli zararlardan CAELINUS AI sorumlu degildir.
\u2022 Hizmet kesintileri veya teknik arizalar icin sorumluluk kabul edilmez.
\u2022 Bu sartlar Turkiye Cumhuriyeti yasalarina tabidir.`
        }
      ],

      contact: {
        title: "Iletisim",
        content: "Kullanim sartlari hakkinda sorulariniz icin:",
        email: "legal@caelinus.com"
      },

      consent: "Bu uygulamayi kullanarak, bu kullanim sartlarini kabul etmis olursunuz."
    },
    en: {
      title: "Terms of Use",
      subtitle: "Service conditions and responsibilities",
      lastUpdated: `Last updated: January 20, 2026`,
      intro: `These terms of use govern the use of the AskSanri application ("app") provided by CAELINUS AI ("we"). By using the app, you agree to these terms.`,

      sections: [
        {
          icon: FileText,
          title: "Service Description",
          content: `AskSanri is an AI-powered personal development and self-reflection tool.

\u2022 The app offers features such as consciousness analysis, symbol interpretation, ritual guidance, and numerology.
\u2022 All content is generated by artificial intelligence and is for general informational purposes.
\u2022 The app is NOT a professional psychology, medical, legal, or financial advisory service.
\u2022 Users should evaluate app content at their own discretion and responsibility.`
        },
        {
          icon: AlertTriangle,
          title: "User Responsibilities",
          content: `\u2022 You agree to use the app in compliance with applicable laws.
\u2022 You are responsible for the security of your account.
\u2022 Creating malicious, misleading, or harmful content is prohibited.
\u2022 You must avoid behavior that negatively affects other users' experience.
\u2022 Individuals under 13 years of age may not use the app.`
        },
        {
          icon: CreditCard,
          title: "Subscriptions and Payments",
          content: `\u2022 The app offers free and premium tiers.
\u2022 Premium subscriptions are managed through the Apple App Store or Google Play Store.
\u2022 Subscriptions auto-renew monthly.
\u2022 Cancellation is done through your device's account settings.
\u2022 Cancelled subscriptions remain active until the end of the current billing period.
\u2022 Refund policy is subject to Apple's and Google's standard refund policies.`
        },
        {
          icon: Scale,
          title: "Intellectual Property",
          content: `\u2022 App content, design, and code belong to CAELINUS AI.
\u2022 Users may not reproduce or distribute content beyond personal use.
\u2022 AI-generated content is for informational purposes; commercial use requires permission.`
        },
        {
          icon: Globe,
          title: "Limitation of Liability",
          content: `\u2022 The app is provided "as is" without guarantee of specific outcomes.
\u2022 Accuracy of AI-generated content is not guaranteed.
\u2022 CAELINUS AI is not responsible for direct or indirect damages resulting from app use.
\u2022 No liability is accepted for service interruptions or technical failures.
\u2022 These terms are governed by the laws of the Republic of Turkey.`
        }
      ],

      contact: {
        title: "Contact",
        content: "For questions about our terms of use:",
        email: "legal@caelinus.com"
      },

      consent: "By using this app, you agree to these terms of use."
    }
  };

  const t = content[language] || content.tr;

  return (
    <div className="min-h-screen bg-[#0a0a0f] py-8 px-4">
      <div className="max-w-2xl mx-auto">
        <div className="mb-8">
          <Link
            to="/"
            className="inline-flex items-center gap-2 text-white/40 hover:text-white/60 text-sm mb-6"
          >
            <ArrowLeft className="w-4 h-4" />
            {language === "tr" ? "Geri" : "Back"}
          </Link>

          <div className="flex items-center justify-between mb-4">
            <h1
              className="text-3xl text-white font-light"
              style={{ fontFamily: "'Cormorant Garamond', serif" }}
            >
              {t.title}
            </h1>

            <div className="flex gap-2">
              <button
                onClick={() => setLanguage("tr")}
                className={`px-3 py-1 rounded text-sm ${language === "tr" ? "bg-amber-500/20 text-amber-400" : "text-white/40"}`}
              >
                TR
              </button>
              <button
                onClick={() => setLanguage("en")}
                className={`px-3 py-1 rounded text-sm ${language === "en" ? "bg-amber-500/20 text-amber-400" : "text-white/40"}`}
              >
                EN
              </button>
            </div>
          </div>

          <p className="text-white/60">{t.subtitle}</p>
          <p className="text-white/30 text-sm mt-2">{t.lastUpdated}</p>
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="bg-white/5 rounded-xl p-6 border border-white/10 mb-6"
        >
          <p className="text-white/70 leading-relaxed">{t.intro}</p>
        </motion.div>

        {t.sections.map((section, index) => (
          <motion.div
            key={index}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            className="bg-white/5 rounded-xl p-6 border border-white/10 mb-4"
          >
            <div className="flex items-center gap-3 mb-4">
              <div className="p-2 rounded-lg bg-amber-500/10">
                <section.icon className="w-5 h-5 text-amber-500" />
              </div>
              <h2 className="text-lg text-white font-medium">{section.title}</h2>
            </div>
            <div className="text-white/60 text-sm leading-relaxed whitespace-pre-line">
              {section.content}
            </div>
          </motion.div>
        ))}

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="bg-white/5 rounded-xl p-6 border border-white/10 mb-6"
        >
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 rounded-lg bg-indigo-500/10">
              <Globe className="w-5 h-5 text-indigo-400" />
            </div>
            <h2 className="text-lg text-white font-medium">{t.contact.title}</h2>
          </div>
          <p className="text-white/60 text-sm mb-2">{t.contact.content}</p>
          <a
            href={`mailto:${t.contact.email}`}
            className="text-amber-500 hover:text-amber-400 text-sm"
          >
            {t.contact.email}
          </a>
        </motion.div>

        <p className="text-white/30 text-xs text-center">{t.consent}</p>
      </div>
    </div>
  );
};

export default TermsPage;
